 const productData = [
    {
        id: 0,
        img: "/serum1.jpg",
        name: "Skin Brightening Serum",
        price: 41.0,
        category: ["Skin Care"],
        sale: false,
    },
    {
        id: 1,
        img: "/serum2.jpg",
        name: "Brightening Super Activs Skin Serum",
        price: 41.0,
        category: ["Skin Care"],
        sale: false,
    },
    {
        id: 2,
        img: "/serum3.jpg",
        name: "Serum Olim Naturals",
        price: 41.0,
        category: ["Skin Care"],
        sale: true,
    },
    {
        id: 3,
        img: "/serum4.jpg",
        name: "Skin Care Serum Olim Naturals",
        price: 41.0,
        category: ["Skin Care"],
        sale: true,
    },
    {
        id: 4,
        img: "/serum5.jpg",
        name: "Brightening Face Serum",
        price: 42.0,
        category: ["Skin Care"],
        sale: false,
    },
    {
        id: 5,
        img: "/serum06.jpg",
        name: "Glowing Skin Serum",
        price: 40.0,
        category: ["Skin Care"],
        sale: true,
    },
    {
        id: 6,
        img: "/serum7.jpg",
        name: "Glowing Skin Serum",
        price: 35.0,
        category: ["Skin Care"],
        sale: false,
    },
    {
        id: 7,
        img: "/mate lipstic9.jpg",
        name: "PRETRO MATTE LIPSTICK",
        price: 30.0,
        category: ["Lipsticks", "Makeup"],
        sale: true,
    },
    {
        id: 8,
        img: "/mate lipstic10.jpg",
        name: "Matte Cream Lipstick",
        price: 30.0,
        category: ["Lipsticks"],
        sale: false,
    },
    {
        id: 9,
        img: "/mate lipstic11.jpg",
        name: "Liquid Matte Lipstick",
        price: 38.0,
        category: ["Lipsticks"],
        sale: true,
    },
    {
        id: 10,
        img: "/mate lipstic12.jpg",
        name: "Liquid Matte Lipstick",
        price: 42.0,
        category: ["Lipsticks"],
        sale: true,
    },
    {
        id: 11,
        img: "/mate lipstic5.jpg",
        name: "liquid lipstic",
        price: 40.0,
        category: ["Lipsticks", "Makeup"],
        sale: false,
    },
    {
        id: 12,
        img: "/mate lipstic13.jpg",
        name: "Liquid Mate Lipstic",
        price: 38.0,
        category: ["Lipsticks"],
        sale: true,
    },
    {
        id: 13,
        img: "/makeup1.jpg",
        name: "Stunning Eyeshadow Kit",
        price: 40.0,
        category: ["Makeup"],
        sale: false,
    },
    {
        id: 14,
        img: "/makeup2.jpg",
        name: "Nude Eyeshadow Palette",
        price: 38.0,
        category: ["Makeup"],
        sale: true,
    },
    {
        id: 15,
        img: "/makeup3.jpg",
        name: "Light Reflecting Foundation",
        price: 55.0,
        category: ["Makeup"],
        sale: true,
    },
    {
        id: 16,
        img: "/makeup4.jpg",
        name: "Matte Foundation",
        price: 50.0,
        category: ["Makeup"],
        sale: false,
    },
    {
        id: 17,
        img: "/face powder1.jpg",
        name: "Glamorous Face Powder",
        price: 48.0,
        category: ["Makeup"],
        sale: true,
    },
    {
        id: 18,
        img: "/face powder2.jpg",
        name: "High Flawless Face Powder",
        price: 45.0,
        category: ["Makeup"],
        sale: true,
    },
    {
        id: 19,
        img: "/nail polish1.jpg",
        name: "Nail Enamel",
        price: 30.0,
        category: ["Nail & Wax"],
        sale: true,
    },
    {
        id: 20,
        img: "/nail polish2.jpg",
        name: "Matte Nail Polis",
        price: 32.0,
        category: ["Nail & Wax"],
        sale: false,
    },
    {
        id: 21,
        img: "/nail polish8.jpg",
        name: "Buy Perfect Office Nail Polish",
        price: 30.0,
        category: ["Nail & Wax"],
        sale: true,
    },
    {
        id: 22,
        img: "/nail polish4.jpg",
        name: "Perfect Nail Polish",
        price: 32.0,
        category: ["Nail & Wax"],
        sale: false,
    },
    {
        id: 23,
        img: "/nail polish10.jpg",
        name: "Best Selling Nail Polish",
        price: 35.0,
        category: ["Nail & Wax"],
        sale: true,
    },
    {
        id: 24,
        img: "/nail polish9.jpg",
        name: "Best Nail Polish",
        price: 35.0,
        category: ["Nail & Wax"],
        sale: true,
    },
    
]
export default productData;